# OpenAI
OPENAI_API_KEY = "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"

# LangChain / LangSmith
LANGCHAIN_API_KEY = "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"
LANGCHAIN_PROJECT = "pr-trustworthy-green-18"
LANGCHAIN_TRACING_V2 = "true"
LANGCHAIN_ENDPOINT = "https://api.smith.langchain.com"

# Optional: Config file path (fallback is llm_config_espanol.toml)
CONFIG_FILE = "config_natalia_v0.1_teachers.toml"
